# Generated by Django 6.0.1 on 2026-04-12 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('brand_name', models.CharField(blank=True, default='', max_length=100)),
                ('barcode', models.CharField(db_index=True, max_length=100, unique=True)),
                ('sku_code', models.CharField(editable=False, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', help_text="Normalized lowercase category name, e.g. 'beverages'", max_length=100)),
                ('size', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('ABC', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='', max_length=1)),
                ('XYZ', models.CharField(blank=True, choices=[('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], default='', max_length=1)),
                ('VED', models.CharField(blank=True, choices=[('V', 'Vital'), ('E', 'Essential'), ('D', 'Desirable')], default='', max_length=1)),
                ('re_order', models.IntegerField(default=0, help_text='Admin-set reorder point in base units')),
                ('reorder_point', models.IntegerField(default=0, help_text='Calculated reorder point (auto-updated)')),
                ('avg_lead_time', models.FloatField(default=7, help_text='Weighted avg lead time in days (auto-updated)')),
                ('avg_daily_sales', models.FloatField(default=10, help_text='Average daily sales in base units')),
                ('package_type', models.CharField(blank=True, choices=[('POUCH', 'Pouch'), ('BOX', 'Box'), ('BAG', 'Bag')], default='', help_text='POUCH=top shelf, BOX=middle, BAG=bottom', max_length=10)),
                ('base_unit', models.CharField(default='Piece', help_text='Unit for one base item (e.g. Piece, Kg, Litre)', max_length=50)),
                ('purchase_unit', models.CharField(default='Carton', help_text='Unit for purchasing (e.g. Carton, Box, Case)', max_length=50)),
                ('conversion_factor', models.DecimalField(decimal_places=4, default=1, help_text='Base units per purchase unit (e.g. 1 Carton = 24 Pieces)', max_digits=10)),
                ('carton_price', models.DecimalField(decimal_places=2, default=0, help_text='Price per purchase unit (carton) in INR', max_digits=12)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('weight_kg', models.FloatField(default=0, help_text='Weight of one base unit in kg')),
                ('length_cm', models.FloatField(default=0)),
                ('width_cm', models.FloatField(default=0)),
                ('height_cm', models.FloatField(default=0)),
                ('is_first_vendor', models.BooleanField(default=False, help_text='True when only one vendor has ever supplied this product')),
                ('is_multi_vendor', models.BooleanField(default=False, help_text='True when multiple vendors supply this product')),
                ('is_deprecated', models.BooleanField(default=False)),
                ('migrated_from_product_id', models.CharField(blank=True, max_length=10, null=True)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, help_text='Price per base unit — auto-derived: carton_price / conversion_factor', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
