# Generated by Django 5.2.4 on 2026-06-01 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPurchaseRequest',
            fields=[
                ('cpr_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('customer_address', models.TextField(blank=True, default='')),
                ('customer_gstin', models.CharField(blank=True, default='', max_length=15)),
                ('requested_quantity', models.IntegerField(help_text='Base units')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Pending', 'Pending — Awaiting Inventory Check'), ('Stock Confirmed', 'Stock Confirmed by Inventory Manager'), ('Stock Rejected', 'Stock Rejected by Inventory Manager'), ('SO Created', 'Sales Order Created')], default='Pending', max_length=20)),
                ('inventory_notes', models.TextField(blank=True, default='')),
                ('inventory_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cprs_created', to=settings.AUTH_USER_MODEL)),
                ('inventory_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cprs_checked', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cprs', to='products.product')),
            ],
            options={
                'verbose_name': 'Customer Purchase Request',
                'verbose_name_plural': 'Customer Purchase Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('so_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(help_text='Base units')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('status', models.CharField(choices=[('Pending Supervisor', 'Pending — Awaiting Supervisor Approval'), ('Supervisor Approved', 'Approved by Supervisor'), ('Supervisor Rejected', 'Rejected by Supervisor'), ('Payment Pending', 'Payment Pending — Awaiting Finance'), ('Finance Confirmed', 'Confirmed by Finance Director'), ('Pick & Pack', 'Pick & Pack in Progress'), ('Dispatched', 'Dispatched')], default='Pending Supervisor', max_length=25)),
                ('supervisor_notes', models.TextField(blank=True, default='')),
                ('supervisor_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cpr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_order', to='sales.customerpurchaserequest')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='products.product')),
                ('supervisor_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Order',
                'verbose_name_plural': 'Sales Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SOPayment',
            fields=[
                ('payment_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('full', 'Full Payment'), ('advance', 'Advance Payment')], max_length=10)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_due', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('payment_notes', models.TextField(blank=True, default='')),
                ('finance_confirmed', models.BooleanField(default=False)),
                ('finance_notes', models.TextField(blank=True, default='')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finance_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_confirmed', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('so', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='sales.salesorder')),
            ],
            options={
                'verbose_name': 'SO Payment',
                'verbose_name_plural': 'SO Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
