# Generated by Django 5.2.4 on 2026-06-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_customer_customerpurchaserequest_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='barcode_image',
            field=models.TextField(blank=True, default='', help_text='Base64 PNG of Code128 barcode'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='driver_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='vehicle_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
