# Generated by Django 5.2.4 on 2026-06-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesorder_barcode_salesorder_barcode_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='logsheet_printed',
            field=models.BooleanField(default=False),
        ),
    ]
