# Generated by Django 6.0.1 on 2026-04-12 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASN',
            fields=[
                ('asn_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('asn_number', models.CharField(max_length=50, unique=True)),
                ('shipment_date', models.DateField()),
                ('expected_arrival_date', models.DateField()),
                ('vehicle_num', models.CharField(max_length=13)),
                ('driver_name', models.CharField(max_length=25)),
                ('driver_phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ASNItem',
            fields=[
                ('asn_item_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('expected_quantity', models.IntegerField(help_text='Base units')),
                ('shipped_quantity', models.IntegerField(help_text='Base units')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=50)),
                ('manufactured_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('bin_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField(help_text='Max base units')),
                ('current_load', models.IntegerField(default=0)),
                ('max_weight_kg', models.FloatField(default=0)),
                ('current_weight_kg', models.FloatField(default=0)),
                ('volume_cm3', models.FloatField(default=0)),
                ('used_volume_cm3', models.FloatField(default=0)),
                ('distance_from_dispatch', models.FloatField()),
                ('pick_count', models.IntegerField(default=0)),
                ('last_picked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GRN',
            fields=[
                ('grn_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('grn_number', models.CharField(max_length=50, unique=True)),
                ('vendor_name', models.CharField(max_length=150)),
                ('vendor_gstin', models.CharField(blank=True, default='', max_length=15)),
                ('receipt_date', models.DateField()),
                ('status', models.CharField(choices=[('RECEIVED', 'Received by Supervisor'), ('QC_PENDING', 'QC Pending'), ('PUTAWAY_PENDING', 'Putaway Plan Generated — Awaiting Worker Confirmation'), ('COMPLETED', 'Completed')], default='RECEIVED', max_length=20)),
                ('barcode_image', models.TextField(blank=True, default='', help_text='Base64 PNG of Code128 barcode encoding the grn_id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GRNItem',
            fields=[
                ('grn_item_id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('received_cartons', models.IntegerField(default=0)),
                ('received_quantity', models.IntegerField(help_text='Base units')),
                ('accepted_quantity', models.IntegerField(default=0)),
                ('rejected_quantity', models.IntegerField(default=0)),
                ('snapshot_product_name', models.CharField(max_length=255)),
                ('snapshot_size', models.CharField(blank=True, default='', max_length=50)),
                ('snapshot_barcode', models.CharField(max_length=100)),
                ('snapshot_package_type', models.CharField(max_length=10)),
                ('snapshot_base_unit', models.CharField(max_length=50)),
                ('snapshot_purchase_unit', models.CharField(max_length=50)),
                ('snapshot_conversion_factor', models.DecimalField(decimal_places=4, max_digits=10)),
                ('snapshot_carton_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('snapshot_gst_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('snapshot_weight_kg', models.FloatField(default=0)),
                ('snapshot_length_cm', models.FloatField(default=0)),
                ('snapshot_width_cm', models.FloatField(default=0)),
                ('snapshot_height_cm', models.FloatField(default=0)),
                ('snapshot_abc', models.CharField(blank=True, default='', max_length=1)),
                ('snapshot_xyz', models.CharField(blank=True, default='', max_length=1)),
                ('snapshot_ved', models.CharField(blank=True, default='', max_length=1)),
                ('barcode_image', models.TextField(blank=True, default='', help_text='Base64 PNG of Code128 barcode encoding this grn_item_id. Generated after QC approval. Workers scan this for putaway.')),
                ('qc_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('po_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('order_cartons', models.IntegerField()),
                ('order_quantity', models.IntegerField(help_text='Base units')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('pr_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('requested_cartons', models.IntegerField()),
                ('requested_quantity', models.IntegerField(help_text='In base units')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recommended_score', models.FloatField(blank=True, null=True)),
                ('chosen_score', models.FloatField(blank=True, null=True)),
                ('vendor_warning', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Finance Pending', 'Finance Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('is_auto_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PutawayPlan',
            fields=[
                ('plan_id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('planned_quantity', models.IntegerField()),
                ('quantity_placed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Reassigned', 'Reassigned — New bin assigned')], default='Pending', max_length=15)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('rack_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('max_weight_kg', models.FloatField(default=0)),
                ('bin_capacity', models.IntegerField(default=100)),
                ('bin_max_weight_kg', models.FloatField(default=50)),
                ('bin_volume_cm3', models.FloatField(default=125000)),
                ('shelf_count', models.IntegerField(default=3)),
                ('bin_count_per_shelf', models.IntegerField(default=10)),
                ('distance_from_dispatch', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('_shelves_generated', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('shelf_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('position', models.IntegerField(choices=[(1, 'Bottom — Heavy (BAG)'), (2, 'Middle — Medium (BOX)'), (3, 'Top    — Light (POUCH)')])),
                ('max_weight_kg', models.FloatField(default=0)),
                ('volume_cm3', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Base units')),
                ('previous_stock', models.IntegerField()),
                ('new_stock', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zone_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('zone_type', models.CharField(help_text='e.g. Dry, Cold, Frozen, Ambient, Hazmat', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
