# Generated by Django 6.0.1 on 2026-04-12 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
        ('products', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asn',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asns', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='asnitem',
            name='asn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Inventory.asn'),
        ),
        migrations.AddField(
            model_name='asnitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asn_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='batch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product'),
        ),
        migrations.AddField(
            model_name='batch',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='grn',
            name='asn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grns', to='Inventory.asn'),
        ),
        migrations.AddField(
            model_name='grn',
            name='qc_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grns_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grn',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grns_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grn',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grns', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grn_items', to='Inventory.batch'),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='grn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Inventory.grn'),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grn_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='Inventory.batch'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='Inventory.bin'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='grn_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_rows', to='Inventory.grnitem'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='products.product'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='grn',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grns', to='Inventory.purchaseorder'),
        ),
        migrations.AddField(
            model_name='asn',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asns', to='Inventory.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='products.product'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='recommended_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_prs', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='pr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='Inventory.purchaserequest'),
        ),
        migrations.AddField(
            model_name='grn',
            name='pr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grns', to='Inventory.purchaserequest'),
        ),
        migrations.AddField(
            model_name='putawayplan',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='putaway_plans', to='Inventory.batch'),
        ),
        migrations.AddField(
            model_name='putawayplan',
            name='bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='putaway_plans', to='Inventory.bin'),
        ),
        migrations.AddField(
            model_name='putawayplan',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_putaways', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='putawayplan',
            name='grn_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='putaway_plans', to='Inventory.grnitem'),
        ),
        migrations.AddField(
            model_name='putawayplan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='putaway_plans', to='products.product'),
        ),
        migrations.AddField(
            model_name='putawayplan',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='putaway_plans', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='putaway_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_rows', to='Inventory.putawayplan'),
        ),
        migrations.AddField(
            model_name='shelf',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='Inventory.rack'),
        ),
        migrations.AddField(
            model_name='bin',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='Inventory.shelf'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='Inventory.batch'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='Inventory.bin'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='rack',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='Inventory.zone'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('vendor', 'product', 'batch_number')},
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'vendor', 'batch', 'bin')},
        ),
    ]
