# Generated by Django 5.2.4 on 2026-05-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnitem',
            name='rejection_images',
            field=models.JSONField(blank=True, default=list, help_text='List of base64-encoded PNG/JPEG strings (up to 5 images).'),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='rejection_notes',
            field=models.TextField(blank=True, default='', help_text='Free-text description of the defect / damage.'),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('Defect', 'Defect'), ('Damaged', 'Damaged'), ('Expired', 'Expired'), ('Wrong Item', 'Wrong Item'), ('Other', 'Other')], default='', help_text='Primary reason for rejection.', max_length=20),
        ),
    ]
