# Generated by Django 5.2.4 on 2026-05-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_grn_item_rejection_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asn',
            name='asn_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
