# Generated by Django 5.2.4 on 2026-05-07 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_asn_number_blank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grnitem',
            name='rejection_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='rejection_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='rejection_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejections_confirmed', to=settings.AUTH_USER_MODEL),
        ),
    ]
