# Generated by Django 6.0.3 on 2026-05-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_grnitem_total_price_grnitem_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='manager_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
