# Generated by Django 5.2.4 on 2026-05-25 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_purchaserequest_manager_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='manager_notes',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='rejection_reason',
        ),
    ]
