# Generated by Django 5.2.3 on 2026-06-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0009_remove_purchaserequest_manager_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
