# Generated by Django 5.2.3 on 2026-06-02 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0010_stockmovement_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='notes',
        ),
    ]
