"""
inventory/admin.py

Django admin registrations for the Inventory app.

Models registered:
  Zone, Rack, Shelf (read-only), Bin (read-only)
  Batch
  Inventory         (read-only — written only via putaway confirmation)
  StockMovement     (read-only — written only by system)
  PurchaseRequest
  PurchaseOrder     (read-only — written only when PR is approved)
  ASN + ASNItem
  GRN + GRNItem
  PutawayPlan

Design decisions:
  - Inventory, StockMovement, PurchaseOrder are read-only in admin
    (system-managed via API flows).
  - Shelf and Bin are read-only (auto-generated by Rack.save()).
  - GRNItem is inline under GRN for context, and also standalone.
  - PutawayPlan is standalone; no inline under GRN (too many rows).
"""

from django.contrib import admin
from django.db.models import Sum
from django.utils.html import format_html

from .models import (
    ASN,
    ASNItem,
    Batch,
    Bin,
    GRN,
    GRNItem,
    Inventory,
    PurchaseOrder,
    PurchaseRequest,
    PutawayPlan,
    Rack,
    Shelf,
    StockMovement,
    Zone,
)


# ─────────────────────────────────────────────
# ZONE
# ─────────────────────────────────────────────

@admin.register(Zone)
class ZoneAdmin(admin.ModelAdmin):
    list_display  = ["zone_id", "zone_type", "rack_count_display",
                     "total_volume_display", "created_at"]
    search_fields = ["zone_id", "zone_type"]
    readonly_fields = ["rack_count_display", "total_volume_display",
                       "total_weight_display", "created_at"]
    ordering      = ["zone_id"]

    def rack_count_display(self, obj):
        return obj.rack_count
    rack_count_display.short_description = "Racks"

    def total_volume_display(self, obj):
        return f"{obj.total_volume_cm3:,.0f} cm³"
    total_volume_display.short_description = "Total Volume"

    def total_weight_display(self, obj):
        return f"{obj.total_weight_kg:,.1f} kg"
    total_weight_display.short_description = "Total Max Weight"


# ─────────────────────────────────────────────
# RACK
# ─────────────────────────────────────────────

@admin.register(Rack)
class RackAdmin(admin.ModelAdmin):
    list_display  = ["rack_id", "zone", "shelf_count", "bin_count_per_shelf",
                     "bin_capacity", "bin_volume_cm3", "bin_max_weight_kg",
                     "distance_from_dispatch", "created_at"]
    list_filter   = ["zone"]
    search_fields = ["rack_id", "zone__zone_id"]
    readonly_fields = [
        "_shelves_generated", "created_at",
        "shelf_count_actual", "bin_count_total",
    ]
    ordering      = ["rack_id"]

    fieldsets = [
        ("Location", {
            "fields": ["rack_id", "zone", "distance_from_dispatch"],
        }),
        ("Shelf / Bin Template", {
            "description": (
                "These values are used when auto-generating shelves and bins. "
                "shelf_count must be divisible by 3."
            ),
            "fields": [
                "shelf_count", "bin_count_per_shelf",
                "bin_capacity", "bin_max_weight_kg", "bin_volume_cm3",
                "max_weight_kg",
            ],
        }),
        ("Auto-generation Status", {
            "classes": ["collapse"],
            "fields": ["_shelves_generated", "shelf_count_actual", "bin_count_total"],
        }),
        ("Meta", {
            "fields": ["created_at"],
        }),
    ]

    def shelf_count_actual(self, obj):
        return obj.shelves.count()
    shelf_count_actual.short_description = "Shelves Created"

    def bin_count_total(self, obj):
        return Bin.objects.filter(shelf__rack=obj).count()
    bin_count_total.short_description = "Bins Created"


# ─────────────────────────────────────────────
# SHELF  (read-only)
# ─────────────────────────────────────────────

@admin.register(Shelf)
class ShelfAdmin(admin.ModelAdmin):
    list_display  = ["shelf_id", "rack", "position", "get_position_display",
                     "max_weight_kg", "volume_cm3", "created_at"]
    list_filter   = ["position", "rack__zone"]
    search_fields = ["shelf_id", "rack__rack_id", "rack__zone__zone_id"]
    readonly_fields = ["shelf_id", "rack", "position", "max_weight_kg",
                       "volume_cm3", "created_at"]
    ordering      = ["shelf_id"]

    def has_add_permission(self, request):
        return False

    def has_change_permission(self, request, obj=None):
        return False


# ─────────────────────────────────────────────
# BIN  (read-only structural data; loads updated by system)
# ─────────────────────────────────────────────

@admin.register(Bin)
class BinAdmin(admin.ModelAdmin):
    list_display  = ["bin_id", "shelf", "zone_display",
                     "current_load", "capacity", "available_units_display",
                     "current_weight_kg", "max_weight_kg",
                     "distance_from_dispatch", "pick_count"]
    list_filter   = ["shelf__rack__zone", "shelf__position"]
    search_fields = ["bin_id", "shelf__shelf_id", "shelf__rack__rack_id",
                     "shelf__rack__zone__zone_id"]
    readonly_fields = [
        "bin_id", "shelf", "capacity",
        "current_load", "max_weight_kg", "current_weight_kg",
        "volume_cm3", "used_volume_cm3",
        "distance_from_dispatch", "pick_count", "last_picked_at",
        "available_units_display", "available_weight_display",
        "available_volume_display", "created_at",
    ]
    ordering      = ["bin_id"]

    def has_add_permission(self, request):
        return False

    def zone_display(self, obj):
        return obj.shelf.rack.zone.zone_id
    zone_display.short_description = "Zone"

    def available_units_display(self, obj):
        colour = "green" if obj.available_units > 0 else "red"
        return format_html(
            "<span style='color:{};'>{}</span>", colour, obj.available_units
        )
    available_units_display.short_description = "Available Units"

    def available_weight_display(self, obj):
        return f"{obj.available_weight_kg:.2f} kg"
    available_weight_display.short_description = "Available Weight"

    def available_volume_display(self, obj):
        return f"{obj.available_volume_cm3:.0f} cm³"
    available_volume_display.short_description = "Available Volume"


# ─────────────────────────────────────────────
# BATCH
# ─────────────────────────────────────────────

@admin.register(Batch)
class BatchAdmin(admin.ModelAdmin):
    list_display  = ["batch_id", "vendor", "product", "batch_number",
                     "manufactured_date", "expiry_date", "created_at"]
    list_filter   = ["vendor", ("expiry_date", admin.DateFieldListFilter)]
    search_fields = ["batch_id", "batch_number",
                     "vendor__vendor_name", "product__product_name"]
    readonly_fields = ["batch_id", "created_at"]
    ordering      = ["-created_at"]


# ─────────────────────────────────────────────
# INVENTORY  (read-only — managed by putaway confirmation)
# ─────────────────────────────────────────────

@admin.register(Inventory)
class InventoryAdmin(admin.ModelAdmin):
    list_display  = ["inventory_id", "product", "vendor", "batch",
                     "bin", "zone_display", "quantity", "last_update"]
    list_filter   = ["vendor", "bin__shelf__rack__zone",
                     "product__ABC", "product__XYZ", "product__VED"]
    search_fields = ["inventory_id", "product__product_name", "product__barcode",
                     "vendor__vendor_name", "batch__batch_number", "bin__bin_id"]
    readonly_fields = [
        "inventory_id", "product", "vendor", "batch",
        "bin", "quantity", "grn_item", "putaway_plan", "last_update",
    ]
    ordering      = ["-last_update"]

    def zone_display(self, obj):
        return obj.bin.shelf.rack.zone.zone_id
    zone_display.short_description = "Zone"

    def has_add_permission(self, request):
        return False

    def has_change_permission(self, request, obj=None):
        return False


# ─────────────────────────────────────────────
# STOCK MOVEMENT  (read-only — written by system)
# ─────────────────────────────────────────────

@admin.register(StockMovement)
class StockMovementAdmin(admin.ModelAdmin):
    list_display  = ["id", "movement_type", "product", "vendor",
                     "quantity", "previous_stock", "new_stock",
                     "bin", "created_at"]
    list_filter   = ["movement_type", "vendor",
                     ("created_at", admin.DateFieldListFilter)]
    search_fields = ["product__product_name", "product__barcode",
                     "vendor__vendor_name", "bin__bin_id",
                     "batch__batch_number"]
    readonly_fields = [
        "product", "vendor", "batch", "bin",
        "movement_type", "quantity",
        "previous_stock", "new_stock", "created_at",
    ]
    ordering      = ["-created_at"]
    date_hierarchy = "created_at"

    def has_add_permission(self, request):
        return False

    def has_change_permission(self, request, obj=None):
        return False


# ─────────────────────────────────────────────
# PURCHASE REQUEST
# ─────────────────────────────────────────────

@admin.register(PurchaseRequest)
class PurchaseRequestAdmin(admin.ModelAdmin):
    list_display  = ["pr_id", "product", "vendor", "requested_cartons",
                     "requested_quantity", "total_amount",
                     "status", "is_auto_generated",
                     "recommended_vendor", "vendor_warning",
                     "created_at"]
    list_filter   = ["status", "is_auto_generated", "vendor_warning",
                     ("created_at", admin.DateFieldListFilter)]
    search_fields = ["pr_id", "product__product_name", "product__barcode",
                     "vendor__vendor_name"]
    readonly_fields = [
        "pr_id", "requested_quantity", "total_amount",
        "recommended_vendor", "recommended_score",
        "chosen_score", "vendor_warning",
        "is_auto_generated", "created_by",
        "created_at", "updated_at",
    ]
    ordering      = ["-created_at"]
    date_hierarchy = "created_at"
    raw_id_fields = ["product", "vendor", "recommended_vendor"]

    fieldsets = [
        ("Request", {
            "fields": ["pr_id", "product", "vendor",
                       "requested_cartons", "requested_quantity", "total_amount"],
        }),
        ("Vendor Scoring", {
            "classes": ["collapse"],
            "fields": ["recommended_vendor", "recommended_score",
                       "chosen_score", "vendor_warning"],
        }),
        ("Status", {
            "fields": ["status", "is_auto_generated", "created_by"],
        }),
        ("Timestamps", {
            "classes": ["collapse"],
            "fields": ["created_at", "updated_at"],
        }),
    ]


# ─────────────────────────────────────────────
# PURCHASE ORDER  (read-only — created by PR approval)
# ─────────────────────────────────────────────

@admin.register(PurchaseOrder)
class PurchaseOrderAdmin(admin.ModelAdmin):
    list_display  = ["po_id", "pr", "vendor", "order_cartons",
                     "order_quantity", "total_amount", "created_at"]
    list_filter   = ["vendor", ("created_at", admin.DateFieldListFilter)]
    search_fields = ["po_id", "vendor__vendor_name", "pr__pr_id",
                     "pr__product__product_name"]
    readonly_fields = [
        "po_id", "pr", "vendor",
        "order_cartons", "order_quantity", "total_amount", "created_at",
    ]
    ordering      = ["-created_at"]
    date_hierarchy = "created_at"

    def has_add_permission(self, request):
        return False

    def has_change_permission(self, request, obj=None):
        return False


# ─────────────────────────────────────────────
# ASN + ASN ITEMS
# ─────────────────────────────────────────────

class ASNItemInline(admin.TabularInline):
    model       = ASNItem
    extra       = 1
    raw_id_fields = ["product"]
    readonly_fields = ["asn_item_id", "created_at"]


@admin.register(ASN)
class ASNAdmin(admin.ModelAdmin):
    list_display  = ["asn_id", "asn_number", "po", "vendor",
                     "shipment_date", "expected_arrival_date",
                     "vehicle_num", "driver_name", "created_at"]
    list_filter   = ["vendor", ("shipment_date", admin.DateFieldListFilter)]
    search_fields = ["asn_id", "asn_number", "vendor__vendor_name",
                     "po__po_id", "vehicle_num", "driver_name"]
    readonly_fields = ["asn_id", "created_at"]
    ordering      = ["-created_at"]
    inlines       = [ASNItemInline]


@admin.register(ASNItem)
class ASNItemAdmin(admin.ModelAdmin):
    list_display  = ["asn_item_id", "asn", "product",
                     "expected_quantity", "shipped_quantity", "created_at"]
    search_fields = ["asn_item_id", "asn__asn_number",
                     "product__product_name", "product__barcode"]
    readonly_fields = ["asn_item_id", "created_at"]
    ordering      = ["-created_at"]


# ─────────────────────────────────────────────
# GRN + GRN ITEMS
# ─────────────────────────────────────────────

class GRNItemInline(admin.TabularInline):
    model           = GRNItem
    extra           = 0
    can_delete      = False
    show_change_link = True
    readonly_fields = [
        "grn_item_id", "product",
        "received_cartons", "received_quantity",
        "accepted_quantity", "rejected_quantity",
        "qc_status", "snapshot_product_name", "snapshot_barcode",
        "created_at",
    ]
    fields = [
        "grn_item_id", "product", "batch",
        "received_cartons", "received_quantity",
        "accepted_quantity", "rejected_quantity",
        "qc_status",
    ]


@admin.register(GRN)
class GRNAdmin(admin.ModelAdmin):
    list_display  = ["grn_id", "grn_number", "po", "vendor_name",
                     "vendor_gstin", "receipt_date", "status",
                     "received_by", "qc_verified_by", "created_at"]
    list_filter   = ["status", ("receipt_date", admin.DateFieldListFilter)]
    search_fields = ["grn_id", "grn_number", "vendor_name",
                     "vendor_gstin", "po__po_id"]
    readonly_fields = [
        "grn_id", "pr", "vendor", "vendor_name", "vendor_gstin",
        "received_by", "qc_verified_by",
        "status", "barcode_image_display", "created_at",
    ]
    ordering      = ["-created_at"]
    date_hierarchy = "receipt_date"
    inlines       = [GRNItemInline]

    fieldsets = [
        ("GRN", {
            "fields": ["grn_id", "grn_number", "po", "pr", "asn"],
        }),
        ("Vendor", {
            "fields": ["vendor", "vendor_name", "vendor_gstin"],
        }),
        ("Receipt", {
            "fields": ["receipt_date", "received_by", "qc_verified_by"],
        }),
        ("Status", {
            "fields": ["status"],
        }),
        ("Barcode", {
            "classes": ["collapse"],
            "fields": ["barcode_image_display"],
        }),
        ("Meta", {
            "classes": ["collapse"],
            "fields": ["created_at"],
        }),
    ]

    def barcode_image_display(self, obj):
        if obj.barcode_image:
            return format_html(
                '<img src="data:image/png;base64,{}" style="max-height:60px;" />',
                obj.barcode_image,
            )
        return "—"
    barcode_image_display.short_description = "GRN Barcode"


@admin.register(GRNItem)
class GRNItemAdmin(admin.ModelAdmin):
    list_display  = ["grn_item_id", "grn", "snapshot_product_name",
                     "snapshot_barcode", "received_cartons",
                     "received_quantity", "accepted_quantity",
                     "rejected_quantity", "qc_status", "created_at"]
    list_filter   = ["qc_status",
                     ("created_at", admin.DateFieldListFilter)]
    search_fields = ["grn_item_id", "snapshot_product_name",
                     "snapshot_barcode", "grn__grn_id",
                     "grn__grn_number"]
    readonly_fields = [
        "grn_item_id", "grn", "product", "batch",
        "received_cartons", "received_quantity",
        "snapshot_product_name", "snapshot_size", "snapshot_barcode",
        "snapshot_package_type", "snapshot_base_unit", "snapshot_purchase_unit",
        "snapshot_conversion_factor", "snapshot_carton_price", "snapshot_gst_percent",
        "snapshot_weight_kg", "snapshot_length_cm", "snapshot_width_cm", "snapshot_height_cm",
        "snapshot_abc", "snapshot_xyz", "snapshot_ved",
        "barcode_image_display", "qc_status", "created_at",
    ]
    ordering      = ["-created_at"]

    fieldsets = [
        ("GRN Link", {
            "fields": ["grn_item_id", "grn", "product", "batch"],
        }),
        ("Quantities", {
            "fields": ["received_cartons", "received_quantity",
                       "accepted_quantity", "rejected_quantity", "qc_status"],
        }),
        ("Product Snapshot", {
            "classes": ["collapse"],
            "fields": [
                "snapshot_product_name", "snapshot_size", "snapshot_barcode",
                "snapshot_package_type", "snapshot_base_unit", "snapshot_purchase_unit",
                "snapshot_conversion_factor", "snapshot_carton_price", "snapshot_gst_percent",
                "snapshot_weight_kg", "snapshot_length_cm", "snapshot_width_cm", "snapshot_height_cm",
                "snapshot_abc", "snapshot_xyz", "snapshot_ved",
            ],
        }),
        ("Item Barcode", {
            "classes": ["collapse"],
            "fields": ["barcode_image_display"],
        }),
        ("Meta", {
            "classes": ["collapse"],
            "fields": ["created_at"],
        }),
    ]

    def barcode_image_display(self, obj):
        if obj.barcode_image:
            return format_html(
                '<img src="data:image/png;base64,{}" style="max-height:60px;" />',
                obj.barcode_image,
            )
        return "—"
    barcode_image_display.short_description = "Item Barcode"


# ─────────────────────────────────────────────
# PUTAWAY PLAN
# ─────────────────────────────────────────────

@admin.register(PutawayPlan)
class PutawayPlanAdmin(admin.ModelAdmin):
    list_display  = ["plan_id", "product", "vendor", "batch",
                     "bin", "zone_display",
                     "planned_quantity", "quantity_placed",
                     "completion_pct", "status",
                     "completed_by", "completed_at", "created_at"]
    list_filter   = ["status",
                     "bin__shelf__rack__zone",
                     ("created_at", admin.DateFieldListFilter)]
    search_fields = ["plan_id", "product__product_name", "product__barcode",
                     "vendor__vendor_name", "batch__batch_number",
                     "bin__bin_id", "grn_item__grn__grn_id"]
    readonly_fields = [
        "plan_id", "grn_item", "product", "vendor", "batch", "bin",
        "planned_quantity", "quantity_placed",
        "status", "completed_by", "completed_at",
        "zone_display", "completion_pct", "created_at",
    ]
    ordering      = ["-created_at"]
    date_hierarchy = "created_at"
    raw_id_fields = []   # plan details are fully read-only

    fieldsets = [
        ("Plan", {
            "fields": ["plan_id", "grn_item", "product", "vendor", "batch"],
        }),
        ("Location", {
            "fields": ["bin", "zone_display"],
        }),
        ("Quantities", {
            "fields": ["planned_quantity", "quantity_placed", "completion_pct"],
        }),
        ("Status", {
            "fields": ["status", "completed_by", "completed_at", "notes"],
        }),
        ("Meta", {
            "classes": ["collapse"],
            "fields": ["created_at"],
        }),
    ]

    def zone_display(self, obj):
        try:
            return f"{obj.bin.shelf.rack.zone.zone_id} ({obj.bin.shelf.rack.zone.zone_type})"
        except Exception:
            return "—"
    zone_display.short_description = "Zone"

    def completion_pct(self, obj):
        if obj.planned_quantity == 0:
            return "0 %"
        pct = round(obj.quantity_placed / obj.planned_quantity * 100, 1)
        colour = "green" if pct >= 100 else ("orange" if pct > 0 else "red")
        return format_html("<span style='color:{};'>{} %</span>", colour, pct)
    completion_pct.short_description = "Complete"

    def has_add_permission(self, request):
        return False

    def has_change_permission(self, request, obj=None):
        return False