# Generated by Django 5.2.4 on 2026-04-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WMSAdmin',
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('inventory_manager', 'Inventory Manager'), ('quality_assistant', 'Quality Assistant'), ('finance_director', 'Finance Director'), ('manager', 'Manager'), ('supervisor', 'Supervisor')], max_length=50, unique=True),
        ),
    ]
