# Generated by Django 5.2.3 on 2026-06-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_alter_notification_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('inventory_manager', 'Inventory Manager'), ('quality_assistant', 'Quality Assistant'), ('finance_director', 'Finance Director'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('sales_manager', 'Sales Manager')], max_length=50, unique=True),
        ),
    ]
