# Generated by Django 6.0.1 on 2026-04-12 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Stored lowercase+trimmed. e.g. 'beverages'", max_length=100, unique=True)),
                ('zone_type', models.CharField(choices=[('Dry', 'Dry Storage'), ('Cold', 'Cold Storage'), ('Frozen', 'Frozen Storage'), ('Ambient', 'Ambient'), ('Hazmat', 'Hazardous Materials')], help_text='Zone type this category maps to', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RejectedAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('GSTIN_MISMATCH', 'GSTIN Mismatch'), ('EMAIL_MISMATCH', 'Email Mismatch'), ('MISSING_GSTIN', 'Missing GSTIN'), ('MISSING_EMAIL', 'Missing Email'), ('BOTH_MISMATCH', 'Both GSTIN and Email Mismatch'), ('VALIDATION_ERROR', 'Validation Error')], max_length=30)),
                ('gstin_in_pdf', models.CharField(blank=True, default='', max_length=15)),
                ('email_in_pdf', models.CharField(blank=True, default='', max_length=254)),
                ('vendor_id_provided', models.CharField(blank=True, default='', max_length=10)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('detail', models.TextField(blank=True, default='')),
                ('rejected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-rejected_at'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=150)),
                ('contact_person', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=15)),
                ('gstin', models.CharField(blank=True, help_text='15-char GST Identification Number', max_length=15, null=True, unique=True)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=50)),
                ('state', models.CharField(blank=True, default='', max_length=50)),
                ('country', models.CharField(blank=True, default='India', max_length=50)),
                ('lead_time', models.IntegerField(default=7, help_text='Default vendor lead time in days')),
                ('payment_terms', models.CharField(blank=True, default='', help_text='e.g. Net-30, COD', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['vendor_name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('warehouse_name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=50)),
                ('state', models.CharField(blank=True, default='', max_length=50)),
                ('country', models.CharField(blank=True, default='', max_length=50)),
                ('warehouse_email', models.EmailField(blank=True, default='', max_length=254)),
                ('warehouse_phone', models.CharField(blank=True, default='', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorAgreement',
            fields=[
                ('agreement_id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='vendor_agreements/')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, default='', max_length=150)),
                ('delivery_location', models.CharField(blank=True, default='', max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('barcode', models.CharField(blank=True, default='', max_length=100)),
                ('vendor_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_mapped', models.BooleanField(default=False)),
                ('match_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mapped_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_mappings', to='products.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_products', to='vendors.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='vendor',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='vendors.warehouse'),
        ),
        migrations.CreateModel(
            name='VendorAgreementProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('variant', models.CharField(blank=True, default='', max_length=100)),
                ('sku', models.CharField(blank=True, default='', max_length=100)),
                ('base_unit', models.CharField(default='Piece', max_length=50)),
                ('purchase_unit', models.CharField(default='Carton', max_length=50)),
                ('conversion_factor', models.DecimalField(decimal_places=4, default=1, help_text='Base units per purchase unit', max_digits=10)),
                ('vendor_price', models.DecimalField(decimal_places=2, help_text='Price per purchase unit (carton)', max_digits=12)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('moq', models.IntegerField(default=1, help_text='Min order qty in purchase units')),
                ('lead_time', models.IntegerField(blank=True, help_text='Override vendor default lead time (days)', null=True)),
                ('weight_kg', models.FloatField(default=0, help_text='Weight of one base unit (kg)')),
                ('length_cm', models.FloatField(default=0)),
                ('width_cm', models.FloatField(default=0)),
                ('height_cm', models.FloatField(default=0)),
                ('carton_weight_kg', models.FloatField(default=0, help_text='Gross weight of one carton (kg)')),
                ('carton_length_cm', models.FloatField(default=0)),
                ('carton_width_cm', models.FloatField(default=0)),
                ('carton_height_cm', models.FloatField(default=0)),
                ('is_mapped', models.BooleanField(default=False)),
                ('is_new_product', models.BooleanField(default=False, help_text='True if created fresh via this agreement')),
                ('is_multi_vendor', models.BooleanField(default=False, help_text='True if another vendor also supplies this product')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendors.vendoragreement')),
                ('category', models.ForeignKey(blank=True, help_text='Normalized category — determines zone eligibility', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreement_products', to='vendors.category')),
                ('mapped_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_catalog_entries', to='products.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_products', to='vendors.vendor')),
            ],
            options={
                'ordering': ['product_name'],
                'unique_together': {('vendor', 'agreement', 'barcode')},
            },
        ),
    ]
