# Generated by Django 6.0.3 on 2026-05-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='supplier_id',
            field=models.CharField(blank=True, default='', help_text='Linked Supplier ID (e.g. SUP0001)', max_length=10),
        ),
    ]
