# Generated by Django 5.2.4 on 2026-06-03 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_supplier_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='supplier_id',
        ),
    ]
